---
abstract: 'Create a presentation using Mojolicious'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-SimpleSlides
no_index:
  file:
    - README.pod
provides:
  Mojolicious::Plugin::SimpleSlides:
    file: lib/Mojolicious/Plugin/SimpleSlides.pm
    version: 0.01
requires:
  File::ShareDir: 1.00
  Mojolicious: 3.0
resources:
  bugtracker: http://github.com/jberger/Mojolicious-Plugin-SimpleSlides/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jberger/Mojolicious-Plugin-SimpleSlides
version: 0.01
